# Generated by Django 3.2.23 on 2024-03-17 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_full_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Full Name')),
                ('default_phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('default_street_address1', models.CharField(blank=True, max_length=80, null=True, verbose_name='Address 1')),
                ('default_street_address2', models.CharField(blank=True, max_length=80, null=True, verbose_name='Address 2')),
                ('default_town_or_city', models.CharField(blank=True, max_length=40, null=True, verbose_name='Town/City')),
                ('default_county', models.CharField(blank=True, max_length=80, null=True, verbose_name='County')),
                ('default_postcode', models.CharField(blank=True, max_length=20, null=True, verbose_name='Postcode')),
                ('default_country', django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
