# Generated by Django 3.2.23 on 2024-03-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20240314_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_email',
            field=models.EmailField(blank=True, max_length=30, null=True, verbose_name='e-mail'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_full_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Full Name'),
        ),
    ]
