# Generated by Django 3.2.23 on 2024-02-08 18:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ProductColour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('colour', models.CharField(choices=[('BK', 'Black'), ('CL', 'Charcoal'), ('PK', 'Pink'), ('GN', 'Green'), ('TL', 'Teal'), ('IY', 'Ivory'), ('PE', 'Purple'), ('RD', 'Red'), ('BE', 'Blue'), ('TN', 'Tan')], max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Colours',
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('size', models.CharField(choices=[('0-3', '0-3 Months'), ('3-6', '3-6 Months'), ('6-12', '6-12 Months'), ('12-24', '12-24 Months'), ('T', 'Toddler/Preschooler'), ('C', 'Child(4-10'), ('S', 'Adult Small/Teen'), ('M', 'Adult Medium'), ('L', 'Adult Large')], max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Sizes',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('unique_product_identifier', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('has_sizes', models.BooleanField(blank=True, default=False, null=True)),
                ('learn_product', models.BooleanField(blank=True, default=False)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
                ('colours', models.ManyToManyField(blank=True, to='products.ProductColour')),
                ('sizes', models.ManyToManyField(blank=True, to='products.ProductSize')),
            ],
        ),
    ]
