# Generated by Django 4.2.11 on 2024-03-22 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='learn_product_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs'),
        ),
    ]
