# Generated by Django 3.2.23 on 2024-02-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='unique_product_identifier',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
