# Generated by Django 3.2.23 on 2024-02-08 01:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='colour',
            field=models.CharField(choices=[('B', 'Black')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(choices=[('0-3', '0-3 Months'), ('3-6', '3-6 Months'), ('6-12', '6-12 Months'), ('12-24', '12-24 Months'), ('T', 'Toddler/Preschooler'), ('C', 'Child(4-10'), ('S', 'Adult Small/Teen'), ('M', 'Adult Medium'), ('L', 'Adult Large')], max_length=50),
        ),
    ]
