# Generated by Django 4.2.11 on 2024-04-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_learn_product_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='learn_product_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs', verbose_name='Learn .pdf File'),
        ),
    ]
