# Generated by Django 3.2.23 on 2024-02-08 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20240208_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsize',
            name='colour',
        ),
    ]
