# Generated by Django 3.2.23 on 2024-02-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_has_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='secondary_colour',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
