# Generated by Django 3.2.23 on 2024-02-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_productsize_colour'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('color', models.CharField(choices=[('BK', 'Black'), ('CL', 'Charcoal'), ('PK', 'Pink'), ('GN', 'Green'), ('TL', 'Teal'), ('IY', 'Ivory'), ('PE', 'Purple'), ('RD', 'Red'), ('BE', 'Blue')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, null=True, to='products.ProductSize'),
        ),
        migrations.AddField(
            model_name='product',
            name='colours',
            field=models.ManyToManyField(blank=True, null=True, to='products.ProductColour'),
        ),
    ]
