# Generated by Django 3.2.23 on 2024-02-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20240208_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colours',
            field=models.ManyToManyField(blank=True, to='products.ProductColour'),
        ),
        migrations.AlterField(
            model_name='product',
            name='learn_product',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
