# Generated by Django 3.2.23 on 2024-02-08 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_sizes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcolour',
            options={'verbose_name_plural': 'Colours'},
        ),
        migrations.AlterModelOptions(
            name='productsize',
            options={'verbose_name_plural': 'Sizes'},
        ),
        migrations.RenameField(
            model_name='productcolour',
            old_name='color',
            new_name='colour',
        ),
    ]
